version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: athletes-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: athelete
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: athletes-redis
    ports:
      - "7379:6379"
    restart: unless-stopped
